yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.IndexListView.as_view(), name='index'),
    path('group/<slug:slug>/', views.GroupListView.as_view(), name='group_list'),
    path('profile/<str:username>/', views.ProfileListView.as_view(), name='profile'),
    path('posts/<int:post_id>/', views.PostDetailView.as_view(), name='post_detail'),
    path('create/', views.PostCreateView.as_view(), name='post_create'),
    path('posts/<int:post_id>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
    path('posts/<int:post_id>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('posts/<int:post_id>/comment', views.CommentCreateView.as_view(), name='add_comment'),
    path(
        'posts/<int:post_id>/comment/<int:comment_id>/',
        views.CommentDeleteView.as_view(), name='delete_comment'
    ),
    path('follow/', views.FollowIndexListView.as_view(), name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.FollowCreateView.as_view(),
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.FollowDeleteView.as_view(),
        name='profile_unfollow'
    ),
    path('group_create/', views.GroupCreateView.as_view(), name='group_create'),
    path('group/<slug:slug>/delete/', views.GroupDeleteView.as_view(), name='group_delete'),
    path('liked/', views.like_unlike_post, name='like_unlike_post'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer> 

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light navbar-expand-sm" style="background-color: SkyBlue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
    <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Navigation toggler">
      <span class="navbar-toggler-icon"></span>
    </button>
    {% comment %}
    Меню - список пунктов со стандартными классами Bootsrap.
    Класс nav-pills нужен для выделения активных пунктов 
    {% endcomment %}
    {% with request.resolver_match.view_name as view_name %}
    <div class="navbar-collapse justify-content-end collapse" id="navbarText">
      <ul class="nav nav-pills">
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle fw-semibold {% if view_name == 'posts:post_create' or view_name == 'posts:group_create' %}active{% endif %}"
           data-bs-toggle="dropdown" role="button" aria-expanded="false">Создать
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
              <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"></path>
            </svg>
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'posts:post_create' %}">Новый пост</a></li>
            <li><a class="dropdown-item" href="{% url 'posts:group_create' %}">Новая группа</a></li>
          </ul>
        </li>
        {% endif %}
        <li class="nav-item"> 
          <a class="nav-link fw-semibold {% if view_name  == 'about:author' %}active{% endif %}"
            href="{% url 'about:author' %}">Об авторе
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
              <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path>
            </svg>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link fw-semibold {% if view_name  == 'about:tech' %}active{% endif %}"
          href="{% url 'about:tech' %}">Технологии
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-gear-wide-connected" viewBox="0 0 16 16">
              <path d="M7.068.727c.243-.97 1.62-.97 1.864 0l.071.286a.96.96 0 0 0 1.622.434l.205-.211c.695-.719 1.888-.03 1.613.931l-.08.284a.96.96 0 0 0 1.187 1.187l.283-.081c.96-.275 1.65.918.931 1.613l-.211.205a.96.96 0 0 0 .434 1.622l.286.071c.97.243.97 1.62 0 1.864l-.286.071a.96.96 0 0 0-.434 1.622l.211.205c.719.695.03 1.888-.931 1.613l-.284-.08a.96.96 0 0 0-1.187 1.187l.081.283c.275.96-.918 1.65-1.613.931l-.205-.211a.96.96 0 0 0-1.622.434l-.071.286c-.243.97-1.62.97-1.864 0l-.071-.286a.96.96 0 0 0-1.622-.434l-.205.211c-.695.719-1.888.03-1.613-.931l.08-.284a.96.96 0 0 0-1.186-1.187l-.284.081c-.96.275-1.65-.918-.931-1.613l.211-.205a.96.96 0 0 0-.434-1.622l-.286-.071c-.97-.243-.97-1.62 0-1.864l.286-.071a.96.96 0 0 0 .434-1.622l-.211-.205c-.719-.695-.03-1.888.931-1.613l.284.08a.96.96 0 0 0 1.187-1.186l-.081-.284c-.275-.96.918-1.65 1.613-.931l.205.211a.96.96 0 0 0 1.622-.434l.071-.286zM12.973 8.5H8.25l-2.834 3.779A4.998 4.998 0 0 0 12.973 8.5zm0-1a4.998 4.998 0 0 0-7.557-3.779l2.834 3.78h4.723zM5.048 3.967c-.03.021-.058.043-.087.065l.087-.065zm-.431.355A4.984 4.984 0 0 0 3.002 8c0 1.455.622 2.765 1.615 3.678L7.375 8 4.617 4.322zm.344 7.646.087.065-.087-.065z"></path>
            </svg>
          </a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link link-light fw-semibold {% if view_name  == 'users:password_change' %}active{% endif %}"
          href="{% url 'users:password_change' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light fw-semibold {% if view_name  == 'users:logout' %}active{% endif %}"
          href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          <a class="nav-link link-dark fw-semibold" href="{% url 'posts:profile' user %}"><span class="link-dark">Вы вошли как: </span> {{ user.username }}</a>
        </li>
        <li>
          
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}"
          href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
          href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
        {% endwith %}
      </ul>
    </div>
  </div>
</nav> 

yatube/templates/includes/scripts.html
<script>
    $( document ).ready(function() {
        $('.like-form').submit(function(e){
            e.preventDefault()
            
            const post_id = $(this).attr('id')
            
            const likeText = $(`.like-button${post_id}`).text()
            const trim = $.trim(likeText)

            const url = $(this).attr('action')
            
            let res;
            const likes = $(`.like-count${post_id}`).text()
            const trimCount = parseInt(likes)
            
            $.ajax({
                type: 'POST',
                url: url,
                data: {
                    'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                    'post_id':post_id,
                },
                success: function(response) {
                    if(trim === '❤️') {
                        $(`.like-button${post_id}`).text('🤍')
                        res = trimCount - 1
                    } else {
                        $(`.like-button${post_id}`).text('❤️')
                        res = trimCount + 1
                    }

                    $(`.like-count${post_id}`).text(res)
                },
                error: function(response) {
                    console.log('error', response)
                }
            })

        })
    });
</script>