yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.IndexListView.as_view(), name='index'),
    path('group/<slug:slug>/', views.GroupListView.as_view(), name='group_list'),
    path('profile/<str:username>/', views.ProfileListView.as_view(), name='profile'),
    path('posts/<int:post_id>/', views.PostDetailView.as_view(), name='post_detail'),
    path('create/', views.PostCreateView.as_view(), name='post_create'),
    path('posts/<int:post_id>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
    path('posts/<int:post_id>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('posts/<int:post_id>/comment', views.CommentCreateView.as_view(), name='add_comment'),
    path(
        'posts/<int:post_id>/comment/<int:comment_id>/',
        views.CommentDeleteView.as_view(), name='delete_comment'
    ),
    path('follow/', views.FollowIndexListView.as_view(), name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.FollowCreateView.as_view(),
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.FollowDeleteView.as_view(),
        name='profile_unfollow'
    ),
    path('group_create/', views.GroupCreateView.as_view(), name='group_create'),
    path('group/<slug:slug>/delete/', views.GroupDeleteView.as_view(), name='group_delete'),
    path('liked/', views.like_unlike_post, name='like_unlike_post'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView,
                                       LogoutView,
                                       PasswordChangeView,
                                       PasswordChangeDoneView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView
                                       )

from django.urls import path, reverse_lazy

from . import views


app_name = 'users'


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('logout/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'
         ),
    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login'
         ),
    path('password_change/',
         PasswordChangeView.as_view(
             template_name='users/password_change_form.html',
             success_url=reverse_lazy('users:password_change_done')
         ),
         name='password_change'
         ),
    path('password_change/done/',
         PasswordChangeDoneView.as_view(
             template_name='users/password_change_done.html'
         ),
         name='password_change_done'
         ),
    path('password_reset/',
         PasswordResetView.as_view(
             template_name='users/password_reset_form.html',
             success_url=reverse_lazy('users:password_reset_done')
         ),
         name='password_reset_form'
         ),
    path('password_reset_done/',
         PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'
         ),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html',
             success_url=reverse_lazy('password_reset_complete')
         ),
         name='password_reset_confirm'
         ),
    path('password_reset_complete/',
         PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'
         ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/forms.py
from django import forms

from .models import Group, Post, Comment


# Добавил в форму label и helptext а русском
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text', 'group', 'image')
        labels = {
            'text': 'Текст поста',
            'group': 'Группа'
        }
        help_texts = {
            'text': 'Напишите свой пост здесь',
            'group': 'Выберите нужную группу из списка'
        }

    def clean_text(self):
        data = self.cleaned_data['text']
        if not data:
            raise forms.ValidationError('Пост не может быть пустым!')
        return data
    
class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('title', 'slug', 'description')
        labels = {
                'title': 'Название группы',
                'slug': 'Адрес группы',
                'description': 'Описание группы'
            }
        help_texts = {
                'title': 'Назовите свою группу',
                'slug': (
                    'Введите адрес группы.'
                    ' Допустимы латинские буквы, цифры, дефисы и нижние подчеркивания'
                ),
                'description': 'Введите описание группы (опционально)'
            }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст комментария'
        }
        help_texts = {
            'text': 'Напишите свой коммментарий здесь'
        }

    def clean_text(self):
        data = self.cleaned_data['text']
        if not data:
            raise forms.ValidationError('Комментарий не может быть пустым!')
        return data

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Count
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic.edit import FormMixin
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse


# from core.paginator.my_paginator import paginate
from .models import Post, Group, User, Follow, Comment, Like
from .forms import PostForm, CommentForm, GroupForm


class IndexListView(ListView):
    '''Главная страница с недавно опубликованными постами'''
    template_name ='posts/index.html'
    paginate_by = 10
    queryset = Post.objects.annotate(comments_count=Count('comments'), num_likes=Count('liked')).select_related('author', 'group')
  
    # Function view version    
    # def index(request):
    #     '''Главная страница с недавно опубликованными постами'''
    #     posts = Post.objects.select_related('author', 'group').all()
    #     # Создана отдельня функция с paginator'ом, помещена в core
    #     page_obj = paginate(request, posts)
    #     return render(request, 'posts/index.html', {'page_obj': page_obj})

class GroupListView(IndexListView):
    '''Страница с постами группы'''
    template_name = 'posts/group_list.html'
    
    def get_queryset(self):
        self.group = get_object_or_404(Group, slug=self.kwargs['slug'])
        return self.group.posts.annotate(comments_count=Count('comments'), num_likes=Count('liked')).select_related('author')
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['group'] = self.group
        return context
        
    # Function view version 
    # def group_posts(request, slug):
    #     '''Страница с постами группы'''
    #     group = get_object_or_404(Group, slug=slug)
    #     posts = group.posts.select_related('author').all()
    #     page_obj = paginate(request, posts)
    #     context = {
    #         'group': group,
    #         'page_obj': page_obj,
    #     }
    #     return render(request, 'posts/group_list.html', context)

class ProfileListView(IndexListView):
    '''Профиль автора с его постами'''
    template_name = 'posts/profile.html'
    
    def get_queryset(self):
        self.author = get_object_or_404(User, username=self.kwargs['username'])
        return self.author.posts.annotate(comments_count=Count('comments'), num_likes=Count('liked')).select_related('group')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        following = (self.request.user.is_authenticated
            and self.request.user.follower.filter(author=self.author).exists())
        context['author'], context['following'] = self.author, following
        return context
    
    # Function view version
    # def profile(request, username):
    #     '''Профиль автора с его постами'''
    #     author = get_object_or_404(User, username=username)
    #     posts = author.posts.select_related('group').all()
    #     page_obj = paginate(request, posts)
    #     following = False
    #     if request.user.is_authenticated:
    #         following = request.user.follower.filter(author=author).exists()
    #     context = {
    #         'author': author,
    #         'page_obj': page_obj,
    #         'following': following
    #     }
    #     return render(request, 'posts/profile.html', context)


class PostDetailView(DetailView, FormMixin):
    '''Вывод подробной информации о посте'''
    template_name = 'posts/post_detail.html'
    form_class = CommentForm
    def get_object(self):
        post = get_object_or_404(Post.objects.annotate(num_likes=Count('liked')), pk=self.kwargs['post_id'])
        return post
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = self.get_object().comments.select_related('author').all()
        return context
    

    # Function view version
    # def post_detail(request, post_id):
    #     '''Вывод подробной информации о посте'''
    #     post = get_object_or_404(Post, pk=post_id)
    #     comments = post.comments.select_related('author').all()
    #     form = CommentForm()
    #     context = {
    #         'post': post,
    #         'comments': comments,
    #         'form': form
    #     }
    #     return render(request, 'posts/post_detail.html', context)

# @method_decorator(login_required, name='dispatch')
class PostCreateView(LoginRequiredMixin, CreateView):
    '''Страница создания поста'''
    template_name = 'posts/create_post.html'
    model = Post
    form_class = PostForm
    
    def form_valid(self, form):
        self.post = form.save(commit=False)
        self.post.author = self.request.user
        self.post.save()
        return super().form_valid(form)

    # Function view version
    # @login_required
    # def post_create(request):
    #     '''Страница создания поста'''
    #     form = PostForm(request.POST or None, files=request.FILES or None)
    #     if request.method == 'POST' and form.is_valid():
    #         post = form.save(commit=False)
    #         post.author = request.user
    #         post.save()
    #         return redirect('posts:profile', username=request.user)
    #     return render(request, 'posts/create_post.html', {'form': form})


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    '''Страница редактирования поста'''
    template_name = 'posts/create_post.html'
    model = Post
    form_class = PostForm
    pk_url_kwarg = 'post_id'
    
    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user
        
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if hasattr(self, 'object'):
            kwargs.update({'instance': self.object})
        return kwargs   

    # Function view version    
    # @login_required
    # def post_edit(request, post_id):
    #     '''Страница редактирования поста'''
    #     post = get_object_or_404(Post, pk=post_id)
    #     form = PostForm(
    #         request.POST or None,
    #         files=request.FILES or None,
    #         instance=post
    #     )
    #     if request.method == 'POST' and form.is_valid():
    #         form.save()
    #         return redirect('posts:post_detail', post_id=post_id)
    #     return render(request, 'posts/create_post.html', {'form': form})


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    '''Страница удаления поста'''
    model = Post
    pk_url_kwarg = 'post_id'
    
    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user
    
    def get_success_url(self):
        return reverse('posts:profile', kwargs={'username': self.request.user.username})

    # Function view version 
    # @login_required
    # def post_delete(request, post_id):
    #     '''Удаление поста'''
    #     post = get_object_or_404(Post, pk=post_id)
    #     if post.author != request.user:
    #         return redirect('posts:post_detail', post_id=post_id)
    #     post.delete()
    #     return redirect('posts:profile', username=request.user)


class CommentCreateView(LoginRequiredMixin, CreateView):
    '''Добавление комментариев на странице поста'''
    template_name = 'posts/post_detail.html'
    model = Comment
    form_class = CommentForm
    
    def form_valid(self, form):
        self.comment = form.save(commit=False)
        self.comment.author = self.request.user
        self.comment.post = get_object_or_404(Post, pk=self.kwargs['post_id'])
        self.comment.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('posts:post_detail', kwargs={'post_id': self.kwargs['post_id']})
    

    # Function view version  
    # @login_required
    # def add_comment(request, post_id):
    #     '''Добавление комментариев на странице поста'''
    #     form = CommentForm(request.POST or None)
    #     if form.is_valid():
    #         comment = form.save(commit=False)
    #         comment.author = request.user
    #         comment.post = get_object_or_404(Post, pk=post_id)
    #         comment.save()
    #     return redirect('posts:post_detail', post_id=post_id)


class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    '''Удаление комментария'''
    model = Comment
    form_class = CommentForm
    pk_url_kwarg = 'comment_id'
    
    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user
    
    def get_success_url(self):
        return reverse('posts:post_detail', kwargs={'post_id': self.kwargs['post_id']})


    # Function view version 
    # @login_required
    # def delete_comment(request, post_id, comment_id):
    #     '''Удаление комментария'''
    #     comment = get_object_or_404(Comment, pk=comment_id)
    #     if comment.author != request.user:
    #         return redirect('posts:post_detail', post_id=post_id)
    #     comment.delete()
    #     return redirect('posts:post_detail', post_id=post_id)


class FollowIndexListView(LoginRequiredMixin, IndexListView):
    '''Страница с постами авторов, на которых подписан пользователь'''
    template_name ='posts/follow.html'
    def get_queryset(self):
        queryset = (Post.objects.annotate(comments_count=Count('comments'), num_likes=Count('liked')).select_related('author', 'group')
                .filter(author__following__user=self.request.user))
        return queryset
    
    # Function view version
    # @login_required
    # def follow_index(request):
    #     '''Страница с постами авторов, на которых подписан пользователь'''
    #     posts = (Post.objects.select_related('author', 'group')

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/includes/post_list.html
{% load thumbnail %}
{% load static %}

<article class="border rounded bg-white" style="padding: 15px; margin-bottom: 15px">
  {% csrf_token %}
  <ul>
    {% if not user.is_authenticated %}
      <a href="{% url 'users:login' %}">
        <button style="float:right;" class="btn btn-light like-button{{post.id}}">🤍</button>
      </a>
    {% else %}
      <form action="{% url 'posts:like_unlike_post' %}" method="POST" class='like-form' id='{{post.id}}'>
        {% csrf_token %}
        <input type="hidden" name="post_id" value={{post.id}}>
        <button style="float:right;" type="submit" class="btn btn-light like-button{{post.id}}">
          {% if request.user not in post.liked.all %}
          🤍
          {% else %}
          ❤️
          {% endif %}
        </button>
      </form>
    {% endif %}
    <p class="text-muted"><em>Опубликовано {{ post.created|date:"d E Y г.  G:i" }}</em>
        </p>
    <p> 
      Автор:  
      <strong>
        <a class="text-decoration-none" href="{% url 'posts:profile' post.author %}">
          {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %}</a>
      </strong>
      <span class="like-count{{post.id}} text-muted" style="float:right; margin-right: 20px;"> {{post.num_likes}} </span>
    </p>
    <h5>{{ post.title }} </h5>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2 rounded" src="{{ im.url }}">
  {% endthumbnail %}
  <p class="text-break" style='white-space: pre-wrap'>{{ post.text }}</p>    
  <p>
    {% if show_group and post.group %}
    Группа <a class="text-decoration-none" href="{% url 'posts:group_list' post.group.slug %}"><em>"{{ post.group }}"</em></a><br>
    {% endif %}
    <a href="{% url 'posts:post_detail' post.pk %}" class="btn btn-secondary" style="float:right;">Подробнее</a><br>
  </p>
  {% with post.comments_count as comments_count %}
    {% if comments_count %} 
      <p class="text-end text-muted" style="margin-bottom: 0px;"><small>Комментарии: {{ comments_count }}</small></p> 
    {% endif %}
  {% endwith %}   
</article>

yatube/templates/posts/includes/switcher.html
{% with request.resolver_match.view_name as view_name %}
<nav class="navbar justify-content-end">
  <ul class="nav nav-pills">
    <li class="nav-item">
      <a 
      class="nav-link {% if view_name  == 'posts:index' %}active{% endif %}"
      href="{% url 'posts:index' %}"
      >
      Все посты
    </a>
  </li>
  {% if user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link {% if view_name  == 'posts:follow_index' %}active{% endif %}"
        href="{% url 'posts:follow_index' %}">Посты избранных авторов
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if view_name  == 'posts:profile' and author == request.user %}active{% endif %}"
        href="{% url 'posts:profile' request.user %}">Мои посты
      </a>
    </li>
  {% endif %}
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle {% if view_name  == 'posts:group_list' %}active{% endif %}"
        data-bs-toggle="dropdown" role="button" aria-expanded="false">Посты группы</a>
      <ul class="dropdown-menu">
        {% for group in groups_all %}
          <li><a class="dropdown-item" href="{% url 'posts:group_list' group.slug %}">{{ group.title }}</a></li>
        {% endfor %}
      </ul>
    </li>
  </ul>
</nav>
{% endwith %}   