yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.IndexListView.as_view(), name='index'),
    path('group/<slug:slug>/', views.GroupListView.as_view(), name='group_list'),
    path('profile/<str:username>/', views.ProfileListView.as_view(), name='profile'),
    path('posts/<int:post_id>/', views.PostDetailView.as_view(), name='post_detail'),
    path('create/', views.PostCreateView.as_view(), name='post_create'),
    path('posts/<int:post_id>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
    path('posts/<int:post_id>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('posts/<int:post_id>/comment', views.CommentCreateView.as_view(), name='add_comment'),
    path(
        'posts/<int:post_id>/comment/<int:comment_id>/',
        views.CommentDeleteView.as_view(), name='delete_comment'
    ),
    path('follow/', views.FollowIndexListView.as_view(), name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.FollowCreateView.as_view(),
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.FollowDeleteView.as_view(),
        name='profile_unfollow'
    ),
    path('group_create/', views.GroupCreateView.as_view(), name='group_create'),
    path('group/<slug:slug>/delete/', views.GroupDeleteView.as_view(), name='group_delete'),
    path('liked/', views.like_unlike_post, name='like_unlike_post'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView,
                                       LogoutView,
                                       PasswordChangeView,
                                       PasswordChangeDoneView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView
                                       )

from django.urls import path, reverse_lazy

from . import views


app_name = 'users'


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('logout/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'
         ),
    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login'
         ),
    path('password_change/',
         PasswordChangeView.as_view(
             template_name='users/password_change_form.html',
             success_url=reverse_lazy('users:password_change_done')
         ),
         name='password_change'
         ),
    path('password_change/done/',
         PasswordChangeDoneView.as_view(
             template_name='users/password_change_done.html'
         ),
         name='password_change_done'
         ),
    path('password_reset/',
         PasswordResetView.as_view(
             template_name='users/password_reset_form.html',
             success_url=reverse_lazy('users:password_reset_done')
         ),
         name='password_reset_form'
         ),
    path('password_reset_done/',
         PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'
         ),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html',
             success_url=reverse_lazy('password_reset_complete')
         ),
         name='password_reset_confirm'
         ),
    path('password_reset_complete/',
         PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'
         ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

from core.models import CreatedModel

User = get_user_model()


class Post(CreatedModel):
    title = models.CharField(
        'Заголовок поста',
        max_length = 140,
        help_text='Напишите здесь заголовок поста'
    )
    text = models.TextField(
        'Текст поста',
        help_text='Напишите здесь свой пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
        help_text='Автор поста'
    )
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу для поста'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )
    liked = models.ManyToManyField(
        User,
        related_name='likes',
        default=None,
        blank=True,
        help_text='Пользователи, лайкнувшие пост'
    )
    like_count = models.BigIntegerField(
        'Количество лайков',
        default='0',
        help_text='Счетчик лайков'
        )


    class Meta:
        ordering = ['-created']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.title[:15]
    
    def get_absolute_url(self):
        return reverse('posts:post_detail', args=[self.pk])
    
    # def num_likes(self):
    #     return self.liked.all().count()
    
    # def comments_count(self):
    #     return self.comments.select_related('author').count()
    
    def groups_all(self):
        return self.group_set.select_related('creator')


class Group(CreatedModel):
    title = models.CharField(
        'Название группы',
        max_length=140,
        unique=True,
        help_text='Дайте название для группы'
    )
    slug = models.SlugField(
        'Адрес для страницы группы',
        unique=True,
        help_text='Укажите адрес для страницы группы'
    )
    description = models.TextField(
        'Описание группы',
        blank=True,
        null=True,
        help_text='Дайте описание группы'
    )
    creator = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='created_groups',
        verbose_name='Создатель',
        help_text='Создатель группы'
    )

    class Meta:
        ordering = ['-created']
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('posts:group_list', args=[self.slug])
    

class Comment(CreatedModel):
    post = models.ForeignKey(
        'Post',
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
        help_text='Добавьте комментарий к посту'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
        help_text='Автор комментария'
    )
    text = models.TextField(
        'Текст комментарий',
        help_text='Напишите здесь свой комментарий'
    )

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
        help_text='Подписчик автора'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
        help_text='Автор, на которого подписались'
    )

    class Meta:
        constraints = [
            # Ограничиваем подписку на себя
            models.CheckConstraint(
                check=~models.Q(user=models.F('author')),
                name='user_not_follows_self'
            ),
            # Ограничиваем создание дублирующих подписок
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_follow'
            )
        ]
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

    def __str__(self):
        return f'{self.user.username} подписан на {self.author.username}'

LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)

class Like(models.Model): 
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=8)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.user}-{self.post}-{self.value}'

yatube/posts/forms.py
from django import forms

from .models import Group, Post, Comment


# Добавил в форму label и helptext а русском
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text', 'group', 'image')
        labels = {
            'text': 'Текст поста',
            'group': 'Группа'
        }
        help_texts = {
            'text': 'Напишите свой пост здесь',
            'group': 'Выберите нужную группу из списка'
        }

    def clean_text(self):
        data = self.cleaned_data['text']
        if not data:
            raise forms.ValidationError('Пост не может быть пустым!')
        return data
    
class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('title', 'slug', 'description')
        labels = {
                'title': 'Название группы',
                'slug': 'Адрес группы',
                'description': 'Описание группы'
            }
        help_texts = {
                'title': 'Назовите свою группу',
                'slug': (
                    'Введите адрес группы.'
                    ' Допустимы латинские буквы, цифры, дефисы и нижние подчеркивания'
                ),
                'description': 'Введите описание группы (опционально)'
            }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст комментария'
        }
        help_texts = {
            'text': 'Напишите свой коммментарий здесь'
        }

    def clean_text(self):
        data = self.cleaned_data['text']
        if not data:
            raise forms.ValidationError('Комментарий не может быть пустым!')
        return data

yatube/templates/posts/comment_confirm_delete.html
{% extends "base.html" %}

{% block title %}
  Удаление поста
{% endblock %}

{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Удаление комментария
          </div>
          <div class="card-body"> 
            <form method="post">{% csrf_token %}
              <p>Вы уверены, что хотите удалить комментарий "{{ object }}"?</p>
              <input type="submit" class="btn btn-primary" value="Подтвердить">
              <input type="button" class="btn btn-secondary" style="float:right;" value="Отмена" onclick="history.back()"/> 
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div>
{% endblock %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %}


{% block title %}
  Новый пост
{% endblock %}

{% block content %}
{% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if form.instance.pk %}       
              Редактировать пост
            {% else %}
              Новый пост
            {% endif %}              
          </div>
          <div class="card-body">
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}
            {% if form.instance.pk %}        
              <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' form.instance.pk %}">
            {% else %}
              <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create' %}">
            {% endif %}
                {% csrf_token %}
                {% for field in form %}            
                  <div class="form-group row my-3 p-3">
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                    </label>              
                    {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}                  
                  </div>            
                {% endfor %}
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if form.instance.pk %}
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %} 
                  </button>
                </div>
              </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}Посты избранных авторов{% endblock %}

{% block content %}
<div class="container py-5 col-12 col-md-10">
  <h2>Посты избранных авторов</h2>
  {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      {% with show_group=True %}
        {% include 'posts/includes/post_list.html' %}
      {% endwith %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}  

yatube/templates/posts/group_confirm_delete.html
{% extends "base.html" %}

{% block title %}
  Удаление группы
{% endblock %}

{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Удаление группы
          </div>
          <div class="card-body"> 
            <form method="post">{% csrf_token %}
              <p>Вы уверены, что хотите удалить группу "{{ object }}"?</p>
              <input type="submit" class="btn btn-primary" value="Подтвердить">
              <input type="button" class="btn btn-secondary" style="float:right;" value="Отмена" onclick="history.back()"/> 
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div>
{% endblock %}

yatube/templates/posts/group_create.html
{% extends 'base.html' %}


{% block title %}
  Новая группа
{% endblock %}

{% block content %}
{% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if form.instance.pk %}       
              Редактировать группу
            {% else %}
              Новая группа
            {% endif %}              
          </div>
          <div class="card-body">
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}
            {% if form.instance.pk %}        
              <form method="post" enctype="multipart/form-data" action="{% url 'posts:group_edit' form.instance.pk %}">
            {% else %}
              <form method="post" enctype="multipart/form-data" action="{% url 'posts:group_create' %}">
            {% endif %}
                {% csrf_token %}
                {% for field in form %}            
                  <div class="form-group row my-3 p-3">
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                    </label>              
                    {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}                  
                  </div>            
                {% endfor %}
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if form.instance.pk %}
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %} 
                  </button>
                </div>
              </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %} 
{% load thumbnail %}

{% block title %}Посты сообщества {{ group }}{% endblock %}

{% block content %}
<div class="container py-5 col-12 col-md-10">
  <h2>{{ group }}
    {% if group.creator == request.user %}
      <span><a href="{% url 'posts:group_delete' group.slug %}" class="btn btn-primary" style="float:right;">
        Удалить группу
      </a></span>
    {% endif %}
  </h2>
  <p>{{ group.description }}</p>
  {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      {% with show_group=False %}
        {% include 'posts/includes/post_list.html' %}
      {% endwith %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}  

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% load thumbnail %}
{% load cache %}
{% block title %}Все посты{% endblock %}
{% block content %}
{% cache 10 index_page page_obj.number %}
<div class="container py-5 col-12 col-md-10">
  <h2>Все посты</h2>
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    {% with show_group=True %}
      {% include 'posts/includes/post_list.html' %}
    {% endwith %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endcache %}
{% endblock %}

yatube/templates/posts/post_confirm_delete.html
{% extends "base.html" %}

{% block title %}
  Удаление поста
{% endblock %}

{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Удаление поста
          </div>
          <div class="card-body"> 
            <form method="post">{% csrf_token %}
              <p>Вы уверены, что хотите удалить пост "{{ object }}"?</p>
              <input type="submit" class="btn btn-primary" value="Подтвердить">
              <input type="button" class="btn btn-secondary" style="float:right;" value="Отмена" onclick="history.back()"/> 
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Пост {{post.text|make_list|slice:':30'|join:'' }}{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="container py-5 col-12 col-md-10">
    <article class="row text-dark" style="padding: 20px">
      <aside class="col-12 col-md-3">
        <article class="border rounded bg-white text-dark" style="padding: 15px; margin-left: -10px">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: <br> 
              {{ post.created|date:"d E Y г.  G:i" }} 
            </li>
            {% if post.group %}   
            <li class="list-group-item">
              Группа: {{ post.group }}
              <br>
              <em>
                <a href="{% url 'posts:group_list' post.group.slug %}">
                  Все посты группы
                </a>
              </em>
            </li>
            {% endif %}
            <li class="list-group-item">
              Автор: {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %}
              <br>
              <em>
                <a href="{% url 'posts:profile' post.author %}">
                  Все посты автора
                </a>
              </em>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post.author.posts.count }}</span>
            </li>
            {% if post.author == request.user %}   
              <li class="list-group-item">
                <em>
                  <a href="{% url 'posts:post_edit' post.pk %}">
                    Редактировать пост
                  </a>
                </em>
              </li>
              <li class="list-group-item">
                <em>
                  <a href="{% url 'posts:post_delete' post.pk %}">
                    Удалить пост
                  </a>
                </em>
              </li>
            {% endif %}
          </ul>
        </article>
      </aside>
      <article class="col-12 col-md-9 border rounded bg-white text-dark">
        <br>
        {% if not user.is_authenticated %}
        <a href="{% url 'users:login' %}">
        <button style="float:right;" class="btn btn-light like-button{{post.id}}">🤍</button>
      </a>
      {% else %}
      <form action="{% url 'posts:like_unlike_post' %}" method="POST" class='like-form' id='{{post.id}}'>
        {% csrf_token %}
        <input type="hidden" name="post_id" value={{post.id}}>
        <button style="float:right;" type="submit" class="btn btn-light like-button{{post.id}}">
          {% if request.user not in post.liked.all %}
          🤍
          {% else %}
          ❤️
          {% endif %}
        </button>
      </form>
      {% endif %}
      <h5>{{ post.title }} </h5>
      <br>
      <p class="like-count{{post.id}} text-muted" style="float:right; margin-right: 20px;"> {{post.num_likes}} </p>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2 rounded" src="{{ im.url }}">
        {% endthumbnail %}
        <p class="text-break" style='white-space: pre-wrap'>{{ post.text }}</p>
        {% if user.is_authenticated %}
          <div class="card my-4 mb-2">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
              <form method="post" action="{% url 'posts:add_comment' post.id %}">
                {% csrf_token %}      
                <div class="form-group mb-2">
                  {{ form.text|addclass:'form-control' }}
                </div>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                  <button type="submit" class="btn btn-primary">Отправить</button>
                </div>
              </form>
            </div>
          </div>
        {% endif %}
        {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a class="text-decoration-none" href="{% url 'posts:profile' comment.author.username %}">
                  {% if comment.author.get_full_name %}{{ comment.author.get_full_name }}{% else %}{{ comment.author }}{% endif %}
                </a>
              </h5>
              <p class="text-muted">
                <em>
                  {{ comment.created|date:"d E Y h:i" }}
                </em>
              </p>
              <p class="text-break" style='white-space: pre-wrap'>{{ comment.text }}</p>
                {% if user.is_authenticated and user == comment.author %}
                  <p class="text-end">
                    <a href="{% url 'posts:delete_comment' post.pk comment.pk %}" class="btn btn-light">Удалить</a>
                  </p>
                {% endif %}
            </div>
          </div>
        {% endfor %} 
      </article>
    </article>
  </div> 
{% endblock %}  

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}{{ author.get_full_name }}{% endblock %}
{% block content %}
<div class="container py-5 col-12 col-md-10">
  <h2>{% if author.get_full_name %}{{ author.get_full_name }}{% else %}{{ author }}{% endif %} (всего постов: {{ author.posts.count }})</h2>  
  {% if user != author and following  %}
  <p class="text-start">
    <a
    class="btn btn-lg btn-secondary"
    href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >Отписаться</a>
  </p>
  {% elif user != author %}
  <p class="text-start">
    <a
    class="btn btn-lg btn-primary mb-2"
    href="{% url 'posts:profile_follow' author.username %}" role="button"
    >Подписаться</a>
  </p>
  {% endif %}
  {% include 'posts/includes/switcher.html' %}  
      {% for post in page_obj %}
        {% with show_group=True %}
          {% include 'posts/includes/post_list.html' %}
        {% endwith %}
      {% endfor %}      
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}